import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [value, setValue] = useState<string>("");
  const [troops, setTroops] =
    useState<{ Spearmen: string; Swordsmen: string; Archers: string }>();
  const [error, setError] = useState(false);

  useEffect(() => {
    error && setTimeout(() => setError(false), 1000);
  }, [error]);

  const handleSubmit = async () => {
    try {
      const response = await fetch("/api/troops", {
        method: "POST",
        body: JSON.stringify({ value }),
      });
      const getResponse = await response.json();
      if (getResponse.message) {
        setError(true);
        return;
      }
      setTroops(getResponse);
    } catch (error) {
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Generate Troops App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>Troops</h2>
        <p className={styles.description}>Enter size to generate troop</p>
        {error && <div>{`Invalid Input`}</div>}
        {!!troops && (
          <div className={styles.troops}>
            <div>{`Spearmen ${troops?.Spearmen}`}</div>
            <div>{`Swordsmen ${troops?.Swordsmen}`}</div>
            <div>{`Archers ${troops?.Archers}`}</div>
          </div>
        )}

        <input
          className={styles.input}
          type="number"
          value={value}
          onChange={(e) => setValue(e.target.value)}
        />
        <button className={styles.button} onClick={handleSubmit}>
          Generate
        </button>
      </main>
    </div>
  );
};

export default Home;
